# Generated by Django 6.1.1 on 2026-09-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.CharField(help_text='Краткое описание для карточки проекта', max_length=250)),
                ('description', models.TextField(help_text='Полное описание, показывается на странице проекта')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True, help_text='Ссылка на живую версию проекта, если есть')),
                ('cover_image', models.ImageField(blank=True, help_text='Главное фото для карточки проекта', null=True, upload_to='projects/covers/')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать на главной странице')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проектов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.techstack'),
        ),
    ]
