# Generated by Django 6.1.1 on 2026-09-20 21:39

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_cover_image_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Главное фото для карточки проекта. Форматы: jpg, jpeg, png, webp, gif. До 5 МБ.', null=True, upload_to='projects/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), projects.models.validate_image_size], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Форматы: jpg, jpeg, png, webp, gif. До 5 МБ.', upload_to='projects/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), projects.models.validate_image_size], verbose_name='Изображение'),
        ),
    ]
